name: Tests Calculatrice

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ajouter src au PYTHONPATH
        run: export PYTHONPATH=$PYTHONPATH:./src

      - name: Lancer les tests
        run: pytest tests/
